apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/talkative-talkative-nw: "true"
        io.kompose.service: backend
    spec:
      containers:
        - image: prathameshdoni/quickchat_backend:latest
          name: backend
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /home/vector/Desktop/MyGitRepoProj/quickchat_Data/back_data
              name: b-volume
      restartPolicy: Always
      volumes:
        - name: b-volume
          persistentVolumeClaim:
            claimName: b-volume
status: {}
