apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/talkative-talkative-nw: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - image: prathameshdoni/talkative_frontend:latest
          name: frontend
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /home/vector/Desktop/MyGitRepoProj/TalkATive_Data/front_data
              name: f-volume
      restartPolicy: Always
      volumes:
        - name: f-volume
          persistentVolumeClaim:
            claimName: f-volume
status: {}
